sonar.projectKey=codemie-ui
sonar.projectName=codemie-ui
sonar.exclusions=**/deploy-templates/**,**/charts/**,**/presets/**,**/constants/**,tailwind.config.js,**/templates/**
sonar.test.inclusions=**/*.test.ts
sonar.coverage.exclusions=**/__tests__/**, **/assets/**, *config.js, *config.ts, **.cjs, **/main.js, **/setupTests.ts, **/api.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6606
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S4036
sonar.issue.ignore.multicriteria.e2.resourceKey=scripts/license_headers/check_license_headers.mjs
