// Copyright 2026 EPAM Systems, Inc. ("EPAM")
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { describe, it, expect, vi, beforeEach } from 'vitest'

import {
  getSettingCredsURL,
  getOriginalCredentialType,
  convertCredsToKeyValue,
  getCredentialType,
} from '@/utils/settings'

describe('getSettingCredsURL', () => {
  beforeEach(() => {
    vi.resetModules()
  })
  it('returns URL when found', () => {
    const credentialValues = [
      { key: 'username', value: 'user' },
      { key: 'url', value: 'http://example.com' },
    ]
    expect(getSettingCredsURL(credentialValues, 'github')).toBe('http://example.com')
  })

  it('returns default URL when URL is not in the array', () => {
    const credentialValues = [{ key: 'username', value: 'user' }]
    expect(getSettingCredsURL(credentialValues, 'github')).toBe('AutoGenerated')
  })
})

describe('getOriginalCredentialType', () => {
  it('returns uppercase for special credential types', () => {
    expect(getOriginalCredentialType('aws')).toBe('AWS')
    expect(getOriginalCredentialType('gcp')).toBe('GCP')
  })

  it('returns capitalized for non-special credential types', () => {
    expect(getOriginalCredentialType('github')).toBe('Github')
  })
})

describe('convertCredsToKeyValue', () => {
  it('converts object to key-value array', () => {
    const input = { username: 'user', password: 'pass' }
    const expected = [
      { key: 'username', value: 'user' },
      { key: 'password', value: 'pass' },
    ]
    expect(convertCredsToKeyValue(input)).toEqual(expected)
  })

  it('returns empty array for null input', () => {
    expect(convertCredsToKeyValue(undefined)).toEqual([])
  })

  it('preserves existing key-value structure', () => {
    const input = {
      username: { key: 'username', value: 'user' },
      password: 'pass',
    }
    const expected = [
      { key: 'username', value: 'user' },
      { key: 'password', value: 'pass' },
    ]
    expect(convertCredsToKeyValue(input as any)).toEqual(expected)
  })
})

describe('getCredentialType', () => {
  it('returns jira for generic_jira_tool', () => {
    expect(getCredentialType('generic_jira_tool')).toBe('jira')
  })

  it('returns confluence for generic_confluence_tool', () => {
    expect(getCredentialType('generic_confluence_tool')).toBe('confluence')
  })

  it('returns xray for tools containing xray (case-insensitive)', () => {
    expect(getCredentialType('xray_test_tool')).toBe('xray')
    expect(getCredentialType('generic_xray_tool')).toBe('xray')
    expect(getCredentialType('XRAY')).toBe('xray')
    expect(getCredentialType('Xray_Integration')).toBe('xray')
  })

  it('returns git for github and gitlab', () => {
    expect(getCredentialType('github')).toBe('git')
    expect(getCredentialType('gitlab')).toBe('git')
  })

  it('returns azuredevops for azure_devops_git', () => {
    expect(getCredentialType('azure_devops_git')).toBe('azuredevops')
  })

  it('returns servicenow for tools starting with servicenow', () => {
    expect(getCredentialType('servicenow_tool')).toBe('servicenow')
  })

  it('returns reportportal for tools starting with Report', () => {
    expect(getCredentialType('ReportPortal')).toBe('reportportal')
  })

  it('returns lowercase type for unrecognized tools', () => {
    expect(getCredentialType('CustomTool')).toBe('customtool')
  })
})
