// Copyright 2026 EPAM Systems, Inc. ("EPAM")
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

import { INDEX_TYPES } from '@/constants/dataSources'
import {
  getAvailableCredentialsTypes,
  getSettingCredsURL,
  getOriginalCredentialType,
  convertCredsToKeyValue,
  getCredentialType,
  generateDefaultAlias,
  SETTING_TYPE_PROJECT,
  SETTING_TYPE_USER,
} from '@/utils/settings'

vi.mock('@/utils/enterpriseEdition', () => ({
  isEnterpriseEdition: () => true,
}))

describe('getSettingCredsURL', () => {
  beforeEach(() => {
    vi.resetModules()
  })
  it('returns URL when found', () => {
    const credentialValues = [
      { key: 'username', value: 'user' },
      { key: 'url', value: 'http://example.com' },
    ]
    expect(getSettingCredsURL(credentialValues, 'github')).toBe('http://example.com')
  })

  it('returns default URL when URL is not in the array', () => {
    const credentialValues = [{ key: 'username', value: 'user' }]
    expect(getSettingCredsURL(credentialValues, 'github')).toBe('AutoGenerated')
  })
})

describe('getOriginalCredentialType', () => {
  it('returns uppercase for special credential types', () => {
    expect(getOriginalCredentialType('aws')).toBe('AWS')
    expect(getOriginalCredentialType('gcp')).toBe('GCP')
  })

  it('returns capitalized for non-special credential types', () => {
    expect(getOriginalCredentialType('github')).toBe('Github')
  })
})

describe('convertCredsToKeyValue', () => {
  it('converts object to key-value array', () => {
    const input = { username: 'user', password: 'pass' }
    const expected = [
      { key: 'username', value: 'user' },
      { key: 'password', value: 'pass' },
    ]
    expect(convertCredsToKeyValue(input)).toEqual(expected)
  })

  it('returns empty array for null input', () => {
    expect(convertCredsToKeyValue(undefined)).toEqual([])
  })

  it('preserves existing key-value structure', () => {
    const input = {
      username: { key: 'username', value: 'user' },
      password: 'pass',
    }
    const expected = [
      { key: 'username', value: 'user' },
      { key: 'password', value: 'pass' },
    ]
    expect(convertCredsToKeyValue(input as any)).toEqual(expected)
  })
})

describe('getCredentialType', () => {
  it('returns jira for generic_jira_tool', () => {
    expect(getCredentialType('generic_jira_tool')).toBe('jira')
  })

  it('returns confluence for generic_confluence_tool', () => {
    expect(getCredentialType('generic_confluence_tool')).toBe('confluence')
  })

  it('returns xwiki for tools starting with xwiki', () => {
    expect(getCredentialType('xwiki_list_wikis')).toBe('xwiki')
    expect(getCredentialType('xwiki_get_page')).toBe('xwiki')
  })

  it('returns xray for tools containing xray (case-insensitive)', () => {
    expect(getCredentialType('xray_test_tool')).toBe('xray')
    expect(getCredentialType('generic_xray_tool')).toBe('xray')
    expect(getCredentialType('XRAY')).toBe('xray')
    expect(getCredentialType('Xray_Integration')).toBe('xray')
  })

  it('returns git for github and gitlab', () => {
    expect(getCredentialType('github')).toBe('git')
    expect(getCredentialType('gitlab')).toBe('git')
  })

  it('returns azuredevops for azure_devops_git', () => {
    expect(getCredentialType('azure_devops_git')).toBe('azuredevops')
  })

  it('returns servicenow for tools starting with servicenow', () => {
    expect(getCredentialType('servicenow_tool')).toBe('servicenow')
  })

  it('returns reportportal for tools starting with Report', () => {
    expect(getCredentialType('ReportPortal')).toBe('reportportal')
  })

  it('returns lowercase type for unrecognized tools', () => {
    expect(getCredentialType('CustomTool')).toBe('customtool')
  })
})

describe('getAvailableCredentialsTypes LiteLLM filtering', () => {
  const regularUser = {
    isAdmin: false,
    applicationsAdmin: [],
    applications: ['demo'],
  } as any

  const adminUser = {
    isAdmin: true,
    applicationsAdmin: [],
    applications: ['demo'],
  } as any

  const enabledConfig = [
    { id: 'features:personalLiteLLMIntegrations', settings: { enabled: true } },
  ]

  const disabledConfig = [
    { id: 'features:personalLiteLLMIntegrations', settings: { enabled: false } },
  ]

  it('hides LiteLLM from regular user settings when personal feature is disabled', () => {
    expect(
      getAvailableCredentialsTypes({
        settingType: SETTING_TYPE_USER,
        user: regularUser,
        project: 'demo',
        customerConfig: disabledConfig,
      })
    ).not.toContain('litellm')
  })

  it('shows LiteLLM in regular user settings when personal feature is enabled', () => {
    expect(
      getAvailableCredentialsTypes({
        settingType: SETTING_TYPE_USER,
        user: regularUser,
        project: 'demo',
        customerConfig: enabledConfig,
      })
    ).toContain('litellm')
  })

  it('keeps LiteLLM hidden from regular project settings when personal feature is enabled', () => {
    expect(
      getAvailableCredentialsTypes({
        settingType: SETTING_TYPE_PROJECT,
        user: regularUser,
        project: 'demo',
        customerConfig: enabledConfig,
      })
    ).not.toContain('litellm')
  })

  it('keeps LiteLLM visible for admins when personal feature is disabled', () => {
    expect(
      getAvailableCredentialsTypes({
        settingType: SETTING_TYPE_USER,
        user: adminUser,
        project: 'demo',
        customerConfig: disabledConfig,
      })
    ).toContain('litellm')
  })

  it('hides personal LiteLLM while customer config is not loaded', () => {
    expect(
      getAvailableCredentialsTypes({
        settingType: SETTING_TYPE_USER,
        user: regularUser,
        project: 'demo',
      })
    ).not.toContain('litellm')
  })
})

describe('generateDefaultAlias', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-05-31T16:45:00'))
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('builds alias as {type}-{YYYY-MM-DD_HH-MM}', () => {
    expect(generateDefaultAlias('jira')).toBe('jira-2026-05-31_16-45')
  })

  it('lowercases the type and collapses non-alphanumeric runs to a single dash', () => {
    expect(generateDefaultAlias('GitHub Cloud')).toBe('github-cloud-2026-05-31_16-45')
  })

  it('trims leading and trailing dashes from the type', () => {
    expect(generateDefaultAlias('--jira--')).toBe('jira-2026-05-31_16-45')
  })

  it('returns empty string when type is missing', () => {
    expect(generateDefaultAlias('')).toBe('')
  })

  it('returns empty string when slugified type becomes empty', () => {
    expect(generateDefaultAlias('@@@')).toBe('')
  })

  it('reflects the current datetime in the suffix', () => {
    vi.setSystemTime(new Date('2027-01-09T08:08:00'))
    expect(generateDefaultAlias('git')).toBe('git-2027-01-09_08-08')
  })

  it('converts underscores in INDEX_TYPES.AZURE_DEVOPS_WIKI to dashes', () => {
    expect(generateDefaultAlias(INDEX_TYPES.AZURE_DEVOPS_WIKI)).toBe(
      'azure-devops-wiki-2026-05-31_16-45'
    )
  })

  it('converts underscores in INDEX_TYPES.AZURE_DEVOPS_WORK_ITEM to dashes', () => {
    expect(generateDefaultAlias(INDEX_TYPES.AZURE_DEVOPS_WORK_ITEM)).toBe(
      'azure-devops-work-item-2026-05-31_16-45'
    )
  })

  it('passes through simple INDEX_TYPES values unchanged', () => {
    expect(generateDefaultAlias(INDEX_TYPES.CONFLUENCE)).toBe('confluence-2026-05-31_16-45')
    expect(generateDefaultAlias(INDEX_TYPES.SHAREPOINT)).toBe('sharepoint-2026-05-31_16-45')
    expect(generateDefaultAlias(INDEX_TYPES.FILE)).toBe('file-2026-05-31_16-45')
  })
})
