// Copyright 2026 EPAM Systems, Inc. ("EPAM")
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 18a6bed66daf82dfeda6d2b19ef028901478b9fe6ec1ffe59e5e043e1260aa2a

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from 'react'

export type ThemeName = 'codemie'

export const themeNames: ThemeName[] = ['codemie']

export type KcEnvName = 'KC_ENTRA_TENANT_ID' | 'KC_ENTRA_CLIENT_ID' | 'KC_ENTRA_CLIENT_SECRET'

export const kcEnvNames: KcEnvName[] = [
  'KC_ENTRA_TENANT_ID',
  'KC_ENTRA_CLIENT_ID',
  'KC_ENTRA_CLIENT_SECRET',
]

export const kcEnvDefaults: Record<KcEnvName, string> = {
  KC_ENTRA_TENANT_ID: '',
  KC_ENTRA_CLIENT_ID: '',
  KC_ENTRA_CLIENT_SECRET: '',
}

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import('./login/KcContext').KcContext

declare global {
  interface Window {
    kcContext?: KcContext
  }
}

export const KcLoginPage = lazy(() => import('./login/KcPage'))

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case 'login':
            return <KcLoginPage kcContext={kcContext} />
        }
      })()}
    </Suspense>
  )
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL
