// Copyright 2026 EPAM Systems, Inc. ("EPAM")
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import * as Yup from 'yup'

import { User } from '@/types/entity'

export enum CredentialComponentType {
  input = 'input',
  switch = 'switch',
  textarea = 'textarea',
  select = 'select',
  record = 'record',
  message = 'message',
}

export enum CredentialComponentPosition {
  top = 'top',
  fieldsSection = 'fieldsSection', // default
}

export type GetCredentialsMappingParams = {
  settingType: string
  user: User | null
  project?: string
  checkIfAdminOfAnyProject?: boolean
}

export type CredentialFieldConfig = {
  label?: string | ((values: Record<string, unknown>) => string)
  placeholder?: string | ((values: Record<string, unknown>) => string)
  type?: CredentialComponentType
  help?: string
  sensitive?: boolean
  shouldShow?: (values: Record<string, unknown>) => boolean
  note?: string
  rows?: number
  options?: { value: string; label: string }[]
  position?: CredentialComponentPosition
  validation?: Yup.Schema
  message?: CredentialMessage
  defaultValue?: string | boolean
}

export enum CredentialAccessType {
  ALL = 'all',
  USER_ONLY = 'user_only',
  PROJECT_ONLY = 'project_only',
}

export enum CredentialRoleRestriction {
  GENERAL = 'general',
  ADMIN_ONLY = 'admin_only',
}

export type CredentialMessage = {
  type: 'info' | 'warn' | 'error'
  title: string
  message: string
  link?: {
    url: string
    text: string
  }
  configKey?: string
  shouldShow?: (values: Record<string, unknown>) => boolean
}

export type FieldsManualConfiguration = {
  label: string
  sensitive: boolean
  addText: string
}

export type CredentialTypeConfig = {
  fields: Record<string, CredentialFieldConfig>
  roleRestrictionType?: CredentialRoleRestriction // Defaults to GENERAL
  accessType?: CredentialAccessType // Defaults to ALL
  enterpriseOnly?: boolean // Defaults to false
  defaultUrl?: string // Defaults to 'AutoGenerated'
  testable?: boolean // Defaults to false
  displayName?: string // User-friendly display name (e.g., "X-ray")
  serverEnum?: string // Backend enum value if different from capitalized key (e.g., "Xray" for "xray")
  message?: CredentialMessage
  fieldsSectionTitle?: string // Defaults to 'Authentication'
  fieldsManualConfiguration?: FieldsManualConfiguration // If present, use RecordInput instead of CredentialFields
}

export type CredentialUIMap = Record<string, CredentialTypeConfig>
