apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codemie-ui.configmapName" . }}
  labels:
    {{- include "codemie-ui.labels" . | nindent 4 }}
data:
  config.js: |
    window._env_ = window._env_ || {};
    window._env_ = {
      VITE_API_URL: "{{ .Values.viteApiUrl }}",
      VITE_ENV: "{{ .Values.viteEnv }}",
      VITE_APP_VERSION: "{{ .Values.image.tag | default .Chart.AppVersion }}",
      {{- if .Values.viteBannerMessage }}
      VITE_BANNER_MESSAGE: "{{ .Values.viteBannerMessage }}",
      {{- end }}
      VITE_ENABLE_ANALYTICS: "{{ .Values.viteEnableAnalytics }}",
      VITE_ENABLE_USER_MANAGEMENT: "{{ .Values.viteEnableUserManagement }}",
      VITE_IDP_PROVIDER: "{{ .Values.viteIdpProvider }}",
    };
