apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codemie-ui.configmapName" . }}
  labels:
    {{- include "codemie-ui.labels" . | nindent 4 }}
data:
  config.js: |
    window._env_ = window._env_ || {};
    window._env_ = {
      VITE_API_URL: "{{ .Values.viteApiUrl }}",
      VITE_ENV: "{{ .Values.viteEnv }}",
      VITE_APP_VERSION: "{{ .Values.image.tag | default .Chart.AppVersion }}",
      {{- range $key, $val := .Values.extraConfig }}
      {{ $key }}: "{{ $val }}",
      {{- end }}
    };
